[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python -c \"import os, uvicorn; port=int(os.environ.get('PORT', 8000)); print(f'Starting on port {port}'); uvicorn.run('api.main:app', host='0.0.0.0', port=port, workers=1, log_level='info')\""
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[environments.production]
variables = {}

[environments.production.build]
watchPatterns = ["backend/**"] 